from __future__ import annotations

from .agent_a import build_agent_a_request, validate_agent_a_response
from .agent_b import build_agent_b_cut_input, validate_agent_b_response
from .agent_c import run_agent_c
from .surface_judge import SurfaceJudge, normalize_surface
from .agent_a_runtime import (
    AgentAPostValidationError,
    AgentAResponseParseError,
    AgentARuntimeError,
    AgentARuntimeOutput,
    run_agent_a_runtime,
)
from .agent_b_runtime import (
    DEFAULT_AGENT_B_MODEL,
    DEFAULT_AGENT_B_SYSTEM_PROMPT,
    run_agent_b_all_cuts_parallel,
    run_agent_b_for_cut,
)
from .gemini_client import (
    DEFAULT_AGENT_A_MODEL,
    create_gemini_client,
    get_uploaded_file_name,
    get_uploaded_video_url,
    upload_video_file,
)
from .artifacts import (
    AGENT_A_STAGE_DIR,
    AGENT_B_STAGE_DIR,
    AGENT_C_STAGE_DIR,
    FINAL_STAGE_DIR,
    FULL_VIDEO_ASSET_STAGE_DIR,
    LOCAL_PREPROCESSING_STAGE_DIR,
    RUN_MANIFEST_FILENAME,
    SEGMENT_PREP_STAGE_DIR,
    StageArtifactLoadError,
    StageArtifacts,
    RunManifestLoadError,
    ensure_run_manifest,
    generate_run_id,
    get_stage_dir,
    load_run_manifest,
    load_stage_bundle,
    mark_stage_failed,
    mark_stage_completed,
    require_completed_stage_output,
    write_agent_a_artifacts,
    write_agent_c_artifacts,
    write_run_manifest,
    write_agent_b_artifacts,
    write_stage_failure_artifacts,
    write_full_video_asset_artifacts,
    write_segment_prep_artifacts,
    write_local_preprocessing_artifacts,
)
from .full_video_asset_report import build_full_video_asset_report_html, write_full_video_asset_report
from .segment_prep import run_segment_prep
from .segment_prep_report import build_segment_prep_report_html, write_segment_prep_report
from .stage_03_04_report import build_stage_03_04_report_html, write_stage_03_04_report
from .models import (
    Action,
    AgentARequest,
    AgentAResponse,
    AgentBAllCutsResult,
    AgentCResult,
    AgentBCutInput,
    AgentBCutOutput,
    AgentBResponse,
    AmbienceSource,
    Character,
    Cut,
    ContinuousEvent,
    EntityRegistry,
    FullVideoAssetResult,
    SegmentClip,
    SegmentPrepResult,
    SkippedCut,
    InteractionType,
    KeyObject,
    LoadedStageBundle,
    LocalPreprocessingResult,
    OnsetEvent,
    PipelineResult,
    PreprocessingResult,
    RunManifest,
    StageErrorRecord,
    StageStatus,
    StageWarningsRecord,
    SurfaceJudgment,
    Track,
    TrackManifest,
    TrackType,
    UnresolvedUnknown,
    UnknownResolution,
    VideoMetadata,
    WarningItem,
)
from .merge_rules import canonical_should_merge, default_surface_compatibility
from .preprocessing import (
    collect_local_preprocessing_warnings,
    detect_cuts,
    extract_video_metadata,
    prepare_full_video_asset,
    run_local_preprocessing,
    run_preprocessing,
)
from .preprocessing_report import build_preprocessing_report_html, write_preprocessing_report
from .agent_a_report import build_agent_a_report_html, write_agent_a_report
from .agent_c_report import build_agent_c_report_html, write_agent_c_report
from .synthesizer import synthesize_tracks

__all__ = [
    "Action",
    "AgentARequest",
    "AgentAResponse",
    "AgentBAllCutsResult",
    "AgentCResult",
    "AgentBCutInput",
    "AgentBCutOutput",
    "AgentBResponse",
    "AgentAPostValidationError",
    "AgentAResponseParseError",
    "AgentARuntimeError",
    "AgentARuntimeOutput",
    "AGENT_A_STAGE_DIR",
    "AGENT_B_STAGE_DIR",
    "AGENT_C_STAGE_DIR",
    "AmbienceSource",
    "Character",
    "Cut",
    "ContinuousEvent",
    "EntityRegistry",
    "FINAL_STAGE_DIR",
    "FULL_VIDEO_ASSET_STAGE_DIR",
    "FullVideoAssetResult",
    "SegmentClip",
    "SegmentPrepResult",
    "SkippedCut",
    "InteractionType",
    "KeyObject",
    "LOCAL_PREPROCESSING_STAGE_DIR",
    "LoadedStageBundle",
    "LocalPreprocessingResult",
    "OnsetEvent",
    "PipelineResult",
    "PreprocessingResult",
    "RUN_MANIFEST_FILENAME",
    "RunManifest",
    "RunManifestLoadError",
    "SEGMENT_PREP_STAGE_DIR",
    "StageArtifactLoadError",
    "StageArtifacts",
    "StageErrorRecord",
    "StageStatus",
    "StageWarningsRecord",
    "SurfaceJudgment",
    "SurfaceJudge",
    "Track",
    "TrackManifest",
    "TrackType",
    "UnresolvedUnknown",
    "UnknownResolution",
    "VideoMetadata",
    "WarningItem",
    "build_agent_a_request",
    "build_agent_b_cut_input",
    "build_agent_c_report_html",
    "build_full_video_asset_report_html",
    "build_segment_prep_report_html",
    "build_stage_03_04_report_html",
    "validate_agent_a_response",
    "validate_agent_b_response",
    "canonical_should_merge",
    "collect_local_preprocessing_warnings",
    "detect_cuts",
    "create_gemini_client",
    "DEFAULT_AGENT_A_MODEL",
    "DEFAULT_AGENT_B_MODEL",
    "DEFAULT_AGENT_B_SYSTEM_PROMPT",
    "default_surface_compatibility",
    "ensure_run_manifest",
    "extract_video_metadata",
    "generate_run_id",
    "get_stage_dir",
    "get_uploaded_file_name",
    "get_uploaded_video_url",
    "load_stage_bundle",
    "load_run_manifest",
    "mark_stage_failed",
    "mark_stage_completed",
    "prepare_full_video_asset",
    "require_completed_stage_output",
    "run_local_preprocessing",
    "run_preprocessing",
    "run_segment_prep",
    "run_agent_a_runtime",
    "run_agent_b_all_cuts_parallel",
    "run_agent_b_for_cut",
    "run_agent_c",
    "normalize_surface",
    "upload_video_file",
    "write_full_video_asset_artifacts",
    "write_agent_a_artifacts",
    "write_agent_b_artifacts",
    "write_agent_c_artifacts",
    "write_segment_prep_artifacts",
    "write_segment_prep_report",
    "write_stage_03_04_report",
    "write_full_video_asset_report",
    "write_local_preprocessing_artifacts",
    "write_run_manifest",
    "write_stage_failure_artifacts",
    "build_preprocessing_report_html",
    "write_preprocessing_report",
    "build_agent_a_report_html",
    "write_agent_a_report",
    "write_agent_c_report",
    "synthesize_tracks",
]
