from __future__ import annotations

from .agent_a import build_agent_a_request, validate_agent_a_response
from .agent_a_runtime import (
    AgentAPostValidationError,
    AgentAResponseParseError,
    AgentARuntimeError,
    AgentARuntimeOutput,
    run_agent_a_runtime,
)
from .gemini_client import (
    DEFAULT_AGENT_A_MODEL,
    create_gemini_client,
    get_uploaded_file_uri,
    upload_video_file,
)
from .models import (
    Action,
    AgentARequest,
    AgentAResponse,
    AmbienceSource,
    Character,
    Cut,
    CutEnrichment,
    ContinuousEvent,
    EntityRegistry,
    InteractionType,
    KeyObject,
    OnsetEvent,
    PipelineResult,
    PreprocessingResult,
    Track,
    TrackManifest,
    TrackType,
    UnresolvedUnknown,
    UnknownResolution,
    VideoMetadata,
    WarningItem,
)
from .merge_rules import canonical_should_merge, default_surface_compatibility
from .preprocessing import detect_cuts, extract_video_metadata, run_preprocessing
from .preprocessing_report import build_preprocessing_report_html, write_preprocessing_report
from .synthesizer import synthesize_tracks

__all__ = [
    "Action",
    "AgentARequest",
    "AgentAResponse",
    "AgentAPostValidationError",
    "AgentAResponseParseError",
    "AgentARuntimeError",
    "AgentARuntimeOutput",
    "AmbienceSource",
    "Character",
    "Cut",
    "CutEnrichment",
    "ContinuousEvent",
    "EntityRegistry",
    "InteractionType",
    "KeyObject",
    "OnsetEvent",
    "PipelineResult",
    "PreprocessingResult",
    "Track",
    "TrackManifest",
    "TrackType",
    "UnresolvedUnknown",
    "UnknownResolution",
    "VideoMetadata",
    "WarningItem",
    "build_agent_a_request",
    "validate_agent_a_response",
    "canonical_should_merge",
    "detect_cuts",
    "create_gemini_client",
    "DEFAULT_AGENT_A_MODEL",
    "default_surface_compatibility",
    "extract_video_metadata",
    "get_uploaded_file_uri",
    "run_preprocessing",
    "run_agent_a_runtime",
    "upload_video_file",
    "build_preprocessing_report_html",
    "write_preprocessing_report",
    "synthesize_tracks",
]
